name: Linter

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone repository
        uses: actions/checkout@v2
      - name: Setup Node JS
        uses: actions/setup-node@v2
        with:
          node-version: 12.13.0
      - name: Install dependencies
        run: npm install
      - name: Run eslint
        run: npm run lint
